image: node:12-alpine

stages:
  - update-production

deploy:
  stage: update-production
  only:
    - master  
  before_script:
    - npm install -g @liara/cli
  script:
    - liara deploy -p $PROJECT_NAME --no-project-logs --api-token $TOKEN
